apiVersion: project.azuredevops.jet.crossplane.io/v1alpha1
kind: Project
metadata:
  name: example-project02
spec:
  forProvider:
    description: "Test Project Description"
    visibility: "private"
    versionControl: "Git"
    workItemTemplate: "Agile"
  providerConfigRef:
    name: default